### ISSUE TITLE
很棒帮的脚本，但遇到一些问题希望得到回复

### ISSUE THREAD

**Issue by Mach525** [djzhao627/JSClickBubble#1]
@djzhao627 **你好！**
很棒帮的脚本，但在使用过程中遇到一些问题，希望得到帮助！
我在Chrome下使用Stylish加载了[自定义字体脚本CSS](https://userstyles.org/styles/100473/004-forcemyfonts-chinese-firefoxchromeie-catcat520)以后点击出来的表情都显示为纯色，而禁用CSS后就恢复正常。

另外在52pojie看到你分享了两个变色和随机表情的玩法，如果能做成油猴的选项开关也加进来那就更棒了。

纯色为`$elem.style.color = "#E94F06";` 定义的颜色

**Comment by djzhao627** [comment]
@Mach525 很感谢您的反馈，前些天在准备期末考试，没来得及回复。

至于您说的表情都显示为纯色可能是您设置了页面的字体，而此字体的emoji表情为字符表现形式。

另外两个关于变色和随机表情的建议暂时无法在油猴的控件上添加开关（油猴似乎只支持脚本的 启用/禁用 开关），如果可以希望您能够自行修改JS来实现自己想要的效果，谢谢。

**Comment by Mach525** [comment]
十分感谢您的回复，让我知道问题所在，也祝您生活顺利！
