### ISSUE TITLE
怎样让颜文字循环下去呢？

### ISSUE THREAD

**Issue by littlegolden** [djzhao627/JSClickBubble#2]
您好，小白一个，现版本的颜文字是按顺序出现的，最后一个出现之后，就不会再产生颜文字了。怎样循环呢？

**Comment by djzhao627** [comment]
你好，你可以让计数器达到一定数量之后进行重置，就可以实现循环了

**Comment by littlegolden** [comment]
谢谢你~实现啦

djzhao <notifications@github.com> 于2019年12月26日周四 下午7:33写道：

**Comment by djzhao627** [comment]
不客气
